### ISSUE TITLE
Migrate to async style

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-snippet#12]
I think we should migrate to async style instead of the callback one

The time has come

**Comment by aryanas159** [comment]
Do you want to use fs promises instead of fs?

**Comment by Eomm** [comment]
I dont' understand..

Right now this plugin generate this code:

```
fastify.addHook('onClose', function hook (instance, done) {
  done()
})
```

We could switch to:

```
fastify.addHook('onClose', async function hook (instance) {
  // custom code
})
```
