### ISSUE TITLE
Snippets not working in .ts files

### ISSUE THREAD

**Issue by qbunt** [fastify/fastify-snippet#16]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.19.2

### Node.js version

16.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

MacOS 13.4.1

### Description

Cannot see any of the snippets when I'm in any typescript file. The JS equivalent works totally fine, but would love to be able to use this in ts files.

### Steps to Reproduce

- open any TS file
- search snippets or type `ff` for `ffhello` or similar
- observe no `ff` snippets show up or are suggested

### Expected Behavior

extension should work the same between js and ts

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Eomm** [comment]
It is expected, we don't have any ts snippets:

https://github.com/fastify/fastify-snippet/blob/5c669c814fe70b81cbae39ff80b89f446d0b0773/package.json#L29

https://github.com/fastify/fastify-snippet/blob/main/snippets/snippets-ts.json

**Comment by qbunt** [comment]
@Eomm thank you for hopping on it 💪 I'm a new fastify addict so this is a welcome addition, cheers boys
