### ISSUE TITLE
Rename fastify instance to app

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-snippet#9]
## 🚀 Feature Proposal

As followup
https://github.com/fastify/website/issues/259

## Motivation

Better naming convention

**Comment by hionnode** [comment]
Can I take up this issue...

**Comment by zekth** [comment]
> Can I take up this issue...

Go for it

**Comment by hionnode** [comment]
Just a doubt, should I fork the repo, or push a feature branch

**Comment by climba03003** [comment]
> 
> 
> Just a doubt, should I fork the repo, or push a feature branch

Fork it and make a branch on your fork
You cannot push a feature branch here without permission.

**Comment by dancastillo** [comment]
@Eomm is this still an issue? I see `instance` being used on fastify docs [here](https://www.fastify.io/docs/latest/Reference/Hooks/#onregister)

**Comment by Eomm** [comment]
> @Eomm is this still an issue? I see `instance` being used on fastify docs [here](https://www.fastify.io/docs/latest/Reference/Hooks/#onregister)

I was thing about from:

```
fastify.addSchema()
```

to:

```
app.addSchema()
```

But there are many things that are not mapped yet. I use a lot this snippet repo `ffhello` saves me a lot to help people debug little things
